In [1]:
import numpy as np

In [2]:
#q1
x = [1,2,3,4]
x_np = np.array([x])
x_np

array([[1, 2, 3, 4]])

In [9]:
#q2
x = 1,2,3,4
y= list(x)
print(type(y))
z = np.array(y)
z*4

<class 'list'>


array([ 4,  8, 12, 16])

In [3]:
#q3
x = [1,2,3]
y = x * 2
z = np.array(y)
z[2:4]

array([3, 1])

In [7]:
np.random.seed(834)

grades = ['a','b','c','d','f']

x = np.random.choice(grades, size=10, replace=True, p=[.3, .4, .2, .08, .02])

x.sort()

x

array(['a', 'a', 'b', 'b', 'b', 'b', 'b', 'b', 'c', 'c'], dtype='<U1')

In [11]:
#Part 2 
import numpy as np

covid_orig = np.genfromtxt('https://raw.githubusercontent.com/Btibert3/datasets/master/covid19.csv', delimiter=',')

In [12]:
#Q5
covid_orig.shape

(56, 9)

In [20]:
#q6
covid = covid_orig[1:, 3]
covid[: 5]

array([133606.,   6670., 206048.,  66021., 746113.])

In [35]:
#q7
covid
covid.size
covid_mean = covid.mean()
covid.max()
covid.sum()

6345771.0

In [37]:
#q8
test = (covid< covid_mean)
new_covid = covid[test]
new_covid.size


37