# Simulations

Business decisions often rely on simulations of events/decisions to understand outcomes and calculate risk. Any example?

In [28]:
! pip install matplotlib

In [29]:
# imports
import numpy as np
import random
import matplotlib.pyplot as plt
import scipy
from scipy import stats

%matplotlib inline

# Part 1

We are going to use the `TSLA.csv` file found on QTools

In [30]:
# Quick exercise:  

# run the starter code below
# file, using column, deliminter to divide numebrs, skip header
tsla = np.genfromtxt("TSLA.csv", usecols=5, delimiter=",", skip_header=1)
tsla_delta = np.diff(tsla)
#if no arugmetns given will calulcate change form row to rw 


In [31]:
tsla[:10]

array([50.936001, 59.936001, 65.625999, 65.542   , 63.243999, 63.001999,
       62.984001, 62.661999, 63.493999, 63.444   ])

In [32]:
tsla[-5:]

array([430.829987, 421.940002, 422.640015, 425.790009, 412.505005])

In [33]:
tsla_delta[-5:]

array([ -8.840026,  -8.889985,   0.700013,   3.149994, -13.285004])

In [34]:
# calculate the mean and standard deviation for the dataset tsla_delta
tmean = tsla_delta.mean()
tmean

1.4291264980237153

In [35]:
tsigma = tsla_delta.std()
tsigma

13.166176040917861

In [64]:
stats.describe(tsla_delta)
#gives summary of statistiscs 

DescribeResult(nobs=253, minmax=(-88.11001599999997, 55.64001399999995), mean=1.4291264980237153, variance=174.03608118940954, skewness=-0.8872627772175465, kurtosis=10.14449359960682)

In [59]:
# let's simulate 50 observations using this information
# I am going to refer to this as 1 experiment
days = np.random.normal(tmean, tsigma, 50)
days.shape


(50,)

In [62]:
days.mean()

1.9302691708112725

In [63]:
days.std()

12.232481985080515

In [69]:
# how many days in our simulation were above 5
len(days[days>=5])

17

In [70]:
len(days[days>=5])/len(days)
# percent 

0.34

In [71]:
# actual data
len(tsla_delta[tsla_delta >= 5])

69

In [72]:
len(tsla_delta)

253

In [73]:
# calculate the % of days (real) that were 5 or above
len(tsla_delta[tsla_delta >= 5]) / len(tsla_delta)


0.2727272727272727

In [74]:
# what % of days (simulated) are above 5
len(days[days>=5]) / len(days)

0.34

## Exercise:

We are going to expand above.  

1. Using the same mean/standard deviation calculated for tesla, each experiment will draw and observe 100 days
1. Calculate the number of days where the returns are $7 or more
1. Conduct this experiment a total of 75 times
1. What is the average across all experiments
1. How does this compare to the observed data in `tsla_delta`

In [127]:
experiment = []
for _ in range(75):
    sim_days = np.random.normal(tmean, tsigma, 100)
    sim_successful_days = sim_days[sim_days>=7]
    experiment.append(len(sim_successful_days))

    

In [130]:
experiment_mean = sum(experiment)/len(experiment)
experiment_mean/100
#of the days 

0.3356

In [138]:
tsla_comp = len(tsla_delta[tsla_delta>=7])
tsla_comp/len(tsla_delta)
#comparing sets 


0.22924901185770752

# Part 2 - Coin Flipping (Anything with Yes/No like outcome)

In [ ]:
# basics
SUCCESS_PROB = .5
np.random.choice([0,1], size=1, p=[SUCCESS_PROB, 1-SUCCESS_PROB])

array([1])

In [ ]:
# size = 10 = # of trials.  We will refer to this as 1 run of the experiment:
flip = np.random.choice([0,1], size=10, p=[SUCCESS_PROB, 1-SUCCESS_PROB])
flip

array([1, 0, 0, 1, 1, 0, 0, 1, 1, 1])

In [ ]:
# Sum shows us how many successes in the experiment
flip.sum()

6

In [ ]:
# something a little more practical:
# Let's say in professional sports (hockey) 10% of the shots on net result in a goal

# assume all shots are of equal quality

# let's say a goalie faces 1000 shots.  How many goals (successes) will they let up?

In [ ]:
GOAL_P = .1
shots = np.random.choice([1,0], size=100, p=[GOAL_P, 1-GOAL_P ])
#shots[:5]

In [ ]:
shots[:20]

array([1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0])

In [ ]:
shots.sum()/len(shots)

0.16

## Breakout Room Exercise:

The GM of the Boston Bruins contacted your analytics firm to help understand a shift in strategy they are looking to employ next season.

The team allowed 167 goals last season on 2103 shots.  

Moving forward, the team wants to understand how the following strategy would impact the number of goals allowed:

1.  Shots can be taken from 3 zones, zone A, B and C.
1.  The team wants to employ a strategy to shift where shots are taken from.  They believe that they can restrict their opponents to the following: zone A accounts for 15% of the shots, Zone B accounts for 65% of the shots, and Zone C the remaining 20%
1.  The shot success rates for zone A, B and C are 5%, 10% and 8% respectively
1.  The Bruins expect to allow 2100 shots next season

Run 100 experiments, where for each experiment, there are 2100 shots using the information provided above.

Across the 100 experiments, how many times would the Bruins reduce the number of goals allowed relative to 167 from the prior season?

Would you recommend the strategy?


In [ ]:
# many ways to do this
# break the problem down
# for each shot, we need to pick a zone, and then associate the probability of the shot going in
# each experiment will have 2100 shots
# will run 100 experiments



# Part 3

Let's say we know the number of events that occur in a given timeframe.  We can model this with the poisson distribution.



In [ ]:
# visitors to your website in a given day
# expected value, # of trials


# np.random.poisson(1200)

In [ ]:
# let's simulate for a week, and then a year
week = np.random.poisson(1200, 7)
year = np.random.poisson(1200, 365)
print(week)
#print(year)

In [ ]:
# lets do a quick plot
# you will dive much deeper into plotting in your next course
plt.hist(year)

In [ ]:
# Example

# A cafe owner contacted your analytics firm to help understand capacity

# In a given week, they sell 1250 bagels that are baked in-house
# They will lose money if they do not have enough ingredients to satisfy demand

# Over a 52 week period, how many weeks can they expect to sell 1300 or more bagels?

bagels = np.random.poisson(1250, 52)
plt.hist(bagels)

## Breakout Room Exercise

The same cafe owner from above has re-engaged your analytics firm to help estimate employee expenses which are a function of the number of orders.  

1.  The cafe is open 252 days a year
1.  On average, they have 2200 orders a day
1.  The owner has estimated that they need 1 employee for every 300 orders
1.  The daily cost for an employee is $125/day

Simulate this exercise 100 times.  What is the average annual employee cost?